name: oppgave 16
on:
  push:
    paths:
      - .github/workflow/Oppgave_16.yml
  workflow_dispatch:

jobs:
  job1:
    defaults:
      run:
        shell: pwsh
        working-directory: ${{ github.workspace }}
    runs-on: ubuntu-latest
    steps:
    
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_KURS }}
          enable-AzPSSession: true

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Blackjack script file
        run: ./src/oppgave_10.ps1 "http://nav-deckofcards.herokuapp.com/shuffle"